server {
    listen 7979 ssl;
    http2 on;
    server_name fidonet.corp.potvin.us;

    ssl_certificate     /etc/ssl/tunarr/fullchain.pem;
    ssl_certificate_key /etc/ssl/tunarr/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 1d;

    root  /var/www/html/public;
    index index.php;
    client_max_body_size 20m;

    error_page 497 =301 https://$host:7979$request_uri;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        fastcgi_pass app:9000;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param HTTPS on;
        fastcgi_param SERVER_PORT 7979;
        fastcgi_param REQUEST_SCHEME https;
        fastcgi_param HTTP_X_FORWARDED_PROTO https;
    }

    location ~ /\.(?!well-known).* { deny all; }
}
